alias ga='git add'
alias gb='git branch -v'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gc='git commit'
alias gca='git commit --amend'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git log --oneline'
alias glf='git log --format=fuller --date=iso-strict-local'
alias glg='git log --oneline --graph'
alias gll='git log --date=iso-strict-local'
alias glsf='git ls-files'
alias gmv='git mv'
alias grb='git rebase'
alias grm='git rm'
alias grs='git restore'
alias grst='git reset'
alias grv='git revert'
alias gs='git status --short'
alias gsh='git show'
alias gsl='git status'
alias gw='git switch'
alias l='ls -CF'
alias la='ls -AF'
alias ll='ls -alF'
alias ls='ls --color=auto --time-style=long-iso'
alias py='python3.14 -X utf8 -X warn_default_encoding'
alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"
