alias cm='chezmoi'
alias cmad='chezmoi add'
alias cmap='chezmoi apply'
alias cmd='chezmoi diff'
alias cmup='chezmoi update'
alias g='git'
alias cmg='chezmoi git --'
alias ga='git add'
alias cmga='chezmoi git -- add'
alias gb='git branch -v'
alias cmgb='chezmoi git -- branch -v'
alias gbd='git branch -d'
alias cmgbd='chezmoi git -- branch -d'
alias gbl='git blame'
alias cmgbl='chezmoi git -- blame'
alias gc='git commit'
alias cmgc='chezmoi git -- commit'
alias gca='git commit --amend'
alias cmgca='chezmoi git -- commit --amend'
alias gd='git diff'
alias cmgd='chezmoi git -- diff'
alias gdc='git diff --cached'
alias cmgdc='chezmoi git -- diff --cached'
alias gl='git log --oneline'
alias cmgl='chezmoi git -- log --oneline'
alias glf='git log --format=fuller --date=iso-strict-local'
alias cmglf='chezmoi git -- log --format=fuller --date=iso-strict-local'
alias glg='git log --oneline --graph'
alias cmglg='chezmoi git -- log --oneline --graph'
alias gll='git log --date=iso-strict-local'
alias cmgll='chezmoi git -- log --date=iso-strict-local'
alias glsf='git ls-files'
alias cmglsf='chezmoi git -- ls-files'
alias gmv='git mv'
alias cmgmv='chezmoi git -- mv'
alias grb='git rebase'
alias cmgrb='chezmoi git -- rebase'
alias grm='git rm'
alias cmgrm='chezmoi git -- rm'
alias grs='git restore'
alias cmgrs='chezmoi git -- restore'
alias grst='git reset'
alias cmgrst='chezmoi git -- reset'
alias grv='git revert'
alias cmgrv='chezmoi git -- revert'
alias gs='git status --short'
alias cmgs='chezmoi git -- status --short'
alias gsh='git show'
alias cmgsh='chezmoi git -- show'
alias gsl='git status'
alias cmgsl='chezmoi git -- status'
alias gw='git switch'
alias cmgw='chezmoi git -- switch'
alias l='ls -CF'
alias la='ls -AF'
alias ll='ls -alF'
alias ls='ls --color=auto --time-style=long-iso'
alias py='python3.14 -X utf8 -X warn_default_encoding'
