#!/bin/fish

function prepare_alias
    set -l name $argv[1]
    set -l definition (string join -n ' ' -- $argv[2..])

    # fish
    alias $name=$definition
    set -l func_path $srcd/dot_config/fish/functions/$name.fish
    echo '# Generated by prepare_alias' >$func_path
    functions $name >>$func_path

    # Bash
    echo alias $name=\'$definition\' >>$srcd/dot_aliases.sh

    # Make chezmoi git aliases from git aliases
    set -l def_args (string split -m 1 -n ' ' -- $definition)
    if test $def_args[1] = git
        set -l cm_definition (string join -n ' ' -- chezmoi git '--' $def_args[2])
        alias cm$name=$cm_definition
        set -l cm_func_path $srcd/dot_config/fish/functions/cm$name.fish
        echo '# Generated from a Git alias by prepare_alias' >$cm_func_path
        functions cm$name >>$cm_func_path
        echo alias cm$name=\'$cm_definition\' >>$srcd/dot_aliases.sh
    end
end
