name: checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chezmoi-and-checks-in-ubuntu:
    runs-on: ubuntu-latest
    env:
      SKIP: run-ubuntu-install-script,run-windows-install-script
    defaults:
      run:
        shell: bash --noprofile --norc -euxo pipefail {0}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - name: Install dotfiles and tools
        run: bash ./install.sh
      - name: Check with pre-commit
        run: |
          export PATH="$HOME/.local/share/mise/shims:${HOME}/.cargo/bin:${HOME}/.local/bin:$HOME/go/bin:${PATH}"
          pre-commit run --all
  chezmoi-in-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - name: Install dotfiles and tools
        run: pwsh .\install.ps1
