name: Check code with pre-commit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chezmoi-and-checks-in-ubuntu:
    runs-on: ubuntu-latest
    env:
      FISH_VER: ""
      SKIP: dprint-fmt,actionlint,run-ubuntu-install-script,run-windows-install-script
    defaults:
      run:
        shell: bash --noprofile --norc -euxo pipefail {0}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - name: Install fish from GitHub releases
        run: |
          if [[ -n "${FISH_VER:-}" ]]; then
            tag="${FISH_VER}"
          else
            tag="$(curl -fsS 'https://api.github.com/repos/fish-shell/fish-shell/releases/latest' | jq -r '.tag_name')"
          fi
          url="https://github.com/fish-shell/fish-shell/releases/download/${tag}/fish-${tag}-linux-x86_64.tar.xz"
          mkdir bin
          curl -fsSL "${url}" | tar -xJ --directory=bin
          echo "$(pwd)/bin" >> "${GITHUB_PATH}"
      - uses: dprint/check@v2.3
        with:
          args: --list-different
      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: false
      - name: Check with pre-commit
        run: uvx pre-commit run --all
