name: Install dotfiles on runner
on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "30 04 */6 * *"
      timezone: "Asia/Tokyo"
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-on-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --noprofile --norc -euxo pipefail {0}
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v6
      - name: Install dotfiles and tools
        run: bash ./install.sh
  install-on-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v6
      - name: Install dotfiles and tools
        run: pwsh .\install.ps1
