name: Install fonts
on:
  push:
    branches:
      - main
    paths:
      - scripts/install_fonts.fish
      - .github/workflows/install_fonts.yaml
  pull_request_target:
    branches:
      - main
  schedule:
    - cron: "45 04 */8 * *"
      timezone: "Asia/Tokyo"
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Install fonts on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --noprofile --norc -euxo pipefail {0}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ile-24556/install-fish-shell-from-github@d662a3c452b76f5d2b00b28cac074dcd9a36e4f3 # v1.0.1
      - name: Install fonts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: fish scripts/install_fonts.fish
      - name: List user-installed fonts
        run: |
          tree -a "${XDG_DATA_HOME:-$HOME/.local/share}/fonts"
