name: Install dotfiles
on:
  push:
    branches:
      - main
    paths:
      - install.ps1
      - install.sh
      - scripts/install_fonts.fish
      - .github/workflows/install_dotfiles.yaml
  pull_request_target:
    branches:
      - main
  schedule:
    - cron: "30 04 */6 * *"
      timezone: "Asia/Tokyo"
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    name: Install dotfiles on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --noprofile --norc -euxo pipefail {0}
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dotfiles and tools
        run: bash ./install.sh

      - name: Install fonts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: fish scripts/install_fonts.fish
      - name: List user-installed fonts
        run: |
          tree -a "${XDG_DATA_HOME:-$HOME/.local/share}/fonts"
  windows:
    name: Install dotfiles on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dotfiles and tools
        run: pwsh .\install.ps1
